// Generated by Wrangler on Wed Sep 11 2024 19:30:29 GMT+0200 (centraleuropeisk sommartid)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  KV: KVNamespace;
}
